version: '3.7'

services:
  mosquitto:
    image: eclipse-mosquitto:latest
    user: mosquitto
    volumes:
      - ./mosquitto.conf:/mosquitto/config/mosquitto.conf
    ports:
      - 1883:1883
      - 9001:9001
